# SITE SETUP
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: chb
#  theme_night: chb
  font: minimal
  font_size: M


# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Christine Bauer is EXDIGIT Professor of Interactive Intelligent Systems."
    twitter: 'christine_bauer'
  verification:
    google: 'tvdmEZ0WrN-QEAz6MIcKMQxy_uIi54hcQ17R_XWHJ6o'


# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image: 'sharing'

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo: ''


# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true


# Site footer

footer:
  copyright:
    notice: 'Â© {year} Christine Bauer.'
#    license:
#      enable: true
#      allow_derivatives: false
#      share_alike: true
#      allow_commercial: false


# Localization
locale:
  date_format: '2 January 2006'
  time_format: '15:04'
  address_format: de_int



# Site features

features:
  syntax_highlighter:
    enable: false
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/chbeu/chbeu.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: false
  csp:
    policy: ''
    report_only: false
  permissions:
    policy: >-
      accelerometer=(), camera=(), geolocation=(), gyroscope=(),
      magnetometer=(), microphone=(), payment=(), usb=()      




show_related:
  book: false
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
publications:
  date_format: January 2006
  citation_style: chb
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: false
comments:
  provider: ''
  commentable:
    post: false
    book: false
    project: false
    publication: false
    event: false
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true